export const style = {
  container: {
    margin: '1.2rem 0',
    padding: '1rem',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'start',
    borderRadius: '10px',
    boxShadow: 'rgba(0, 0, 0, 0.2) 0px 2px 10px',
  },
  title: {
    marginBottom: '1rem',
    fontSize: '1.3rem',
    fontWeight: '400',
  },
  author: {
    marginLeft: '1rem',
    color: '#777',
    fontWeight: '300',
    fontStyle: 'italic',
  },
  details: {
    marginTop: '1rem',
  },
  buttons: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-end',
  },
  detailsButton: {
    marginBottom: '.5rem',
    padding: '.2rem .4rem',
    backgroundColor: '#fff',
    border: 'none',
    cursor: 'pointer',
    borderRadius: '5px',
    boxShadow: 'rgba(0, 0, 0, 0.1) 0px 0px 0px 1px',
  },
  link: {
    marginBottom: '.5rem',
    display: 'block',
    color: '#999',
  },
  likeButton: {
    marginBottom: '.5rem',
    padding: '.2rem .4rem',
    border: 'none',
    cursor: 'pointer',
    borderRadius: '5px',
    backgroundColor: '#fff',
    boxShadow: 'rgba(0, 0, 0, 0.1) 0px 0px 0px 1px',
  },
  likeHeart: {
    color: 'tomato',
  },
  removeButton: {
    padding: '.2rem .4rem',
    border: 'none',
    cursor: 'pointer',
    borderRadius: '5px',
    boxShadow: 'rgba(0, 0, 0, 0.1) 0px 0px 0px 1px',
    backgroundColor: '#ff927e',
    color: '#fff',
  },
};
